"""Generate shuffled health enums and direct float-to-enum branches."""

from hashlib import sha256
from pathlib import Path
from random import Random


ROOT = Path(__file__).resolve().parents[1]
HEALTH_DIR = ROOT / "src/main/java/com/mx_wj/protectedentity/health"
MAX_TENTHS = 20_000
VALUES_PER_ENUM = 500
SEED = 0x4D785F776A
ENCODE_MODULUS = 65_521
ENCODE_MULTIPLIER = 40_503
ENCODE_OFFSET = 49_237
FLOAT_OFFSET = 4096.375
FLOAT_SCALE = 32.0
DECODE_MULTIPLIER = pow(ENCODE_MULTIPLIER, -1, ENCODE_MODULUS)


def constant_name(tenths):
    digest = sha256(("protectedentity-health-v1:%d" % tenths).encode("ascii")).hexdigest()
    return "V_" + digest[:16].upper()


def float_literal(tenths):
    return "%d.%dF" % divmod(tenths, 10)


def encoded_amount_literal(tenths):
    code = (tenths * ENCODE_MULTIPLIER + ENCODE_OFFSET) % ENCODE_MODULUS
    encoded = FLOAT_OFFSET + code / FLOAT_SCALE
    literal = ("%.5f" % encoded).rstrip("0").rstrip(".")
    if "." not in literal:
        literal += ".0"
    return literal + "F"


indices = list(range(MAX_TENTHS + 1))
Random(SEED).shuffle(indices)
names = {index: constant_name(index) for index in indices}
assert len(set(names.values())) == len(indices)
assert all(((index * ENCODE_MULTIPLIER + ENCODE_OFFSET) % ENCODE_MODULUS
            - ENCODE_OFFSET) * DECODE_MULTIPLIER % ENCODE_MODULUS == index
           for index in indices)

chunks = [indices[start:start + VALUES_PER_ENUM]
          for start in range(0, len(indices), VALUES_PER_ENUM)]
locations = {}
for chunk_number, chunk in enumerate(chunks):
    for index in chunk:
        locations[index] = "HealthValue.Set%02d.%s" % (chunk_number, names[index])

value_lines = [
    "package com.mx_wj.protectedentity.health;",
    "",
    "// Generated by tools/generate_health_values.py. The float amount is encoded, not health.",
    "public sealed interface HealthValue permits",
]
for number in range(len(chunks)):
    suffix = " {" if number == len(chunks) - 1 else ","
    value_lines.append("        HealthValue.Set%02d%s" % (number, suffix))
value_lines.append("    float amount();")

for number, chunk in enumerate(chunks):
    value_lines.extend(["", "    enum Set%02d implements HealthValue {" % number])
    for position, index in enumerate(chunk):
        suffix = ";" if position == len(chunk) - 1 else ","
        value_lines.append("        %s(%s)%s" % (names[index], encoded_amount_literal(index), suffix))
    value_lines.extend([
        "",
        "        private final float amount;",
        "",
        "        Set%02d(float amount) {" % number,
        "            this.amount = amount;",
        "        }",
        "",
        "        @Override",
        "        public float amount() {",
        "            return this.amount;",
        "        }",
        "    }",
    ])
value_lines.append("}")

lookup_lines = [
    "package com.mx_wj.protectedentity.health;",
    "",
    "// Generated by tools/generate_health_values.py. No ordinal or lookup array is used.",
    "public final class HealthValueLookup {",
    "    private HealthValueLookup() {",
    "    }",
    "",
    "    public static HealthValue fromFloat(float health, String internalId,",
    "                                        int randomA, int randomB, int checkValue) {",
    "        if (internalId == null || internalId.isEmpty()",
    "                || HealthCalculator.checkValue(health, internalId, randomA, randomB) != checkValue) {",
    "            return null;",
    "        }",
    "        float clamped = Float.isNaN(health) ? 0.0F",
    "                : Math.max(0.0F, Math.min(health, HealthCalculator.MAX_HEALTH));",
    "        float rounded = Math.round(clamped * 10.0F) / 10.0F;",
]

lookup_chunks = [list(range(start, min(start + VALUES_PER_ENUM, MAX_TENTHS + 1)))
                 for start in range(0, MAX_TENTHS + 1, VALUES_PER_ENUM)]
for number in range(len(lookup_chunks) - 1):
    boundary = (number + 1) * VALUES_PER_ENUM
    lookup_lines.append("        if (rounded < %s) return Segment%02d.find(rounded);" %
                        (float_literal(boundary), number))
lookup_lines.extend([
    "        return Segment%02d.find(rounded);" % (len(lookup_chunks) - 1),
    "    }",
])

for number, chunk in enumerate(lookup_chunks):
    checks = list(chunk)
    Random(SEED + number + 1).shuffle(checks)
    lookup_lines.extend([
        "",
        "    private static final class Segment%02d {" % number,
        "        private static HealthValue find(float health) {",
    ])
    for index in checks:
        lookup_lines.append("            if (health == %s) return %s;" %
                            (float_literal(index), locations[index]))
    lookup_lines.extend([
        '            throw new IllegalStateException("Unmapped health: " + health);',
        "        }",
    "    }",
    ])
lookup_lines.append("}")

(HEALTH_DIR / "HealthValue.java").write_text("\n".join(value_lines) + "\n", encoding="utf-8")
(HEALTH_DIR / "HealthValueLookup.java").write_text("\n".join(lookup_lines) + "\n", encoding="utf-8")
print("Generated %d shuffled enum constants and %d direct lookup branches." %
      (len(indices), len(indices)))
